#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("aves.Droid.Resource", IsApplication=true)]

namespace aves.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int tono1 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int tono2 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int tono3 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int tono4 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int tono5 = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_info = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_menu = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_launcher_activity = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_menu_equipo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_habitats = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_morfologia = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_recomendacion = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_menu_sonido = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_menu_tipo = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public const int btnImgExpander = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int imgProfilePic = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int ivMenuImg = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int menuIconImgView = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int menuListView = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int titleBarLinearLayout = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int txtActionBarText = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int txtDescription = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int txtMnuText = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int txtPage = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Menu = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int BaseTema = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
